services:
  contao.bootstrap.form.form_layout.factory:
    class: ContaoBootstrap\Form\FormLayout\BootstrapFormLayoutFactory
    arguments:
      - '@contao_bootstrap.environment'
      - '%netzmacht.contao_form_designer.widgets%'
      - '%netzmacht.contao_form_designer.defaults%'
    tags:
      - { name: 'netzmacht.contao_form_designer.factory' }

  contao.bootstrap.form.input_groups_migration:
    class: ContaoBootstrap\Form\Migration\InputGroupsGroupIndexMigration
    arguments:
      - '@database_connection'
    tags:
      - {name: 'contao.migration'}
