<?php

/**
 * @package    contao-bootstrap
 * @author     David Molineus <david.molineus@netzmacht.de>
 * @copyright  2015 netzmacht creative David Molineus
 * @license    LGPL 3.0
 * @filesource
 *
 */

namespace Netzmacht\Bootstrap\Form\Subscriber;

use Contao\Widget;
use Netzmacht\Bootstrap\Core\Bootstrap;
use Netzmacht\Contao\FormHelper\Event\ViewEvent;
use Netzmacht\Html\Element;

/**
 * This class renders Contao standard forms which are not generated by the form generator.
 *
 * @package Netzmacht\Bootstrap\Form\Subscriber
 */
class ContaoFormsRenderer extends AbstractSubscriber
{
    /**
     * Handle the view event.
     *
     * @param ViewEvent $event The view event.
     *
     * @return void
     */
    public function handle(ViewEvent $event)
    {
        // Form model exists, break here.
        if ($event->getFormModel() || !Bootstrap::isEnabled()) {
            return;
        }

        $widget  = $event->getWidget();
        $element = $event->getView()->getContainer()->getElement();

        if (!$element instanceof Element) {
            return;
        }

        $this->addSearchOptionToLargeSelects($widget, $element);
    }

    /**
     * Enable the live search feature for selects with a large number of options.
     *
     * @param Widget  $widget  Form widget.
     * @param Element $element Form element.
     *
     * @return void
     */
    private function addSearchOptionToLargeSelects(Widget $widget, Element $element)
    {
        $config = Bootstrap::getConfig();

        if ($widget->type !== 'select'
            || !$config->get('form.styled-select.enabled')
            || !static::getWidgetConfigValue($config, $widget->type, 'styled-select')
        ) {
            return;
        }

        if (is_array($widget->options)
            && $config->get('form.styled-select.search-threshold')
            && count($widget->options) >= $config->get('form.styled-select.search-threshold')) {
            $element->setAttribute('data-live-search', true);
        }
    }
}
